package pl.tysia.maggstone.constants

enum class AccessibleFunctionsTypes {
    MENU_TILE_CHANGE_LOCATION,
    MENU_TILE_CATALOG_CONTACTORS,
    MENU_TILE_CATALOG_WARES,
    MENU_TILE_DOCUMENT_OFFER,
    MENU_TILE_DOCUMENT_PACKING,
    MENU_TILE_DOCUMENT_RECEIVE,
    MENU_TILE_DOCUMENT_SHIFT,
    MENU_TILE_DOCUMENT_ORDER,
    MENU_TILE_FIND_HOSE,
    MENU_TILE_SCAN_WARE,
    MENU_TILE_STOCKTAKING,
}